version: "3"

services:
  app:
    build: ./
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      NODE_ENV: "test"
    command: sh -c "npm install sqlite3 jest && npm start"
  tests:
    build: ./
    depends_on:
      - app
    environment:
      APP_URL: http://app:3001
    command: sh -c "npm install jest && npm run test:integration"    